### ISSUE TITLE
stats on RTMP stream

### ISSUE THREAD

**Issue by wwwyaron** [leandromoreira/clappr-stats#10]
Hi, would this plugin work with RTMP streams as well?
cannot get it to work with clappr RTMP plugin...

**Comment by leandromoreira** [comment]
@wwwyaron if [clappr-rtmp](https://github.com/flavioribeiro/clappr-rtmp-plugin) does implement some [expected events](https://github.com/leandromoreira/clappr-stats/blob/master/index.js#L32-L44) and it should, it should work.

**Comment by leandromoreira** [comment]
do you have any RTMP resource example so I can use it to debug?

**Comment by wwwyaron** [comment]
tnx, good news.
for RTMP plugin, the code is:  plugins: {'playback': [RTMP]}
for STATS plugin, the code is: plugins: [ClapprStats]
any idea how to join then together?

**Comment by leandromoreira** [comment]
`plugins: [ClapprStats, RTMP]`

**Comment by wwwyaron** [comment]
spot on! works beautifully.
many tnx
