### ISSUE TITLE
Handle stop event

### ISSUE THREAD

**Issue by gfronza** [leandromoreira/clappr-stats#7]
Currently, if a user stop a live stream and play it again, this plugin won't report anymore metrics. Should we restart this plugin's state (and collects new metrics) or include counters and timers of `stop`?

**Comment by leandromoreira** [comment]
I vote for restart but I'd like to gather more opinions... @towerz @tjenkinson

**Comment by gfronza** [comment]
@leandromoreira me too. One thing I noticed, the startup time after restarting the state is always lower (usually by half). This can mess up with the metrics.

**Comment by leandromoreira** [comment]
I think that a new `startup_time` is really  faster :D that's the reality

**Comment by gfronza** [comment]
@leandromoreira can I take up this one? On ENDED event I would restart the state of the plugin.

**Comment by leandromoreira** [comment]
@gfronza sure thing! Thank you very much!
